### ISSUE TITLE
Open Data - General Notifications around new datasets and updated datasets. https://data.louisvilleky.gov/data.json

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#8]

**Comment by mgottholsen** [comment]
## New Feature Description:
As an IFTTT user, I want to receive a time-based (daily, weekly, monthly, quarterly) notifications of when new Open Data datasets are published and/or when existing datasets are updated.

**Comment by aplannersguide** [comment]
We set something up for this on our [open data portal twitter account](https://twitter.com/chadataportal) here in Chattanooga. Since we update datasets every night it can get kind of spammy. We would like for it to only show when a new dataset is created but so far haven't figured out how to do this with the json data feed. If you can figure it out we would love to replicate it.

**Comment by mgottholsen** [comment]
Perhaps it makes more sense to just focus on new datasets, as opposed to when things are getting consistently updated...

**Comment by aplannersguide** [comment]
That would be my recommendation. Let me know if you figure out how to set it up as we would like to replicate your IFTTT.

**Comment by mgottholsen** [comment]
## New Feature Description:
As an IFTTT user, I want to receive a time-based (daily, weekly, monthly, quarterly) notifications of when new Open Data datasets are published.

**Comment by mgottholsen** [comment]
As we utilize DKAN, please reference https://dkan.readthedocs.io/en/latest/introduction/index.html for interfacing with the Open Data Portal.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#17
